### ISSUE TITLE
Feature Request - Copy Scale

### ISSUE THREAD

**Issue by stultvox** [Nuzair46/Copy-Bone-Transforms#1]
I'm not sure if this is a bug report or a feature request.

Currently, the addon copies the physical movement of the armature, but does not copy any scaling that might have been done. At least this appears to be the case with imported VRM models I tested with where one has had the bones scaled to adjust their apparent thickness.

Having the option to copy over armature scale would be handy. Alternatively, if the addon copied the scale by default as well, that may work well for most users (if a scale has been applied to the Base, they likely want that applied to the Target).

**Comment by Nuzair46** [comment]
Thanks for using this. I created this for a friend and didn't knew it was used by anyone else. I'll try to add this feature. Also currently I heard from my friend that it is kind of bugged. I will look into this when I get time.

**Comment by stultvox** [comment]
Thank you for making this, and for the quick response! I make a lot of VRM models using VRoid Studio, and edit them afterwards in Blender. This is a really common workflow. Scaling bones is a quick and easy way to add thickness to a model that isn't possible in VRoid Studio. Your Blender Addon has the potential to really speed up this piece of the workflow when there's alternate/new versions of a model. Right now it seems like it would work well for copying posture for rest poses (there's not an easy way to do that in Blender).

As for the bugs, I didn't notice any. But then again, the model I was working with had all the exact same bones and bone names. If I see any issues, I'll be sure to troubleshoot and report them.

Thanks!

**Comment by Nuzair46** [comment]
Your welcome. Currently Im busy with some projects. I will get on this as soon as possible.

**Comment by Nuzair46** [comment]
I have made a new release. Please check it. Thank you for the feedback.
